// Generated by gencpp from file beginner_tutorials/message_rate.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MESSAGE_RATE_H
#define BEGINNER_TUTORIALS_MESSAGE_MESSAGE_RATE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/message_rateRequest.h>
#include <beginner_tutorials/message_rateResponse.h>


namespace beginner_tutorials
{

struct message_rate
{

typedef message_rateRequest Request;
typedef message_rateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct message_rate
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::message_rate > {
  static const char* value()
  {
    return "712d75215ae233049ae50b3899bf1e61";
  }

  static const char* value(const ::beginner_tutorials::message_rate&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::message_rate > {
  static const char* value()
  {
    return "beginner_tutorials/message_rate";
  }

  static const char* value(const ::beginner_tutorials::message_rate&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::message_rateRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::message_rate > 
template<>
struct MD5Sum< ::beginner_tutorials::message_rateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::message_rate >::value();
  }
  static const char* value(const ::beginner_tutorials::message_rateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::message_rateRequest> should match 
// service_traits::DataType< ::beginner_tutorials::message_rate > 
template<>
struct DataType< ::beginner_tutorials::message_rateRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::message_rate >::value();
  }
  static const char* value(const ::beginner_tutorials::message_rateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::message_rateResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::message_rate > 
template<>
struct MD5Sum< ::beginner_tutorials::message_rateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::message_rate >::value();
  }
  static const char* value(const ::beginner_tutorials::message_rateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::message_rateResponse> should match 
// service_traits::DataType< ::beginner_tutorials::message_rate > 
template<>
struct DataType< ::beginner_tutorials::message_rateResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::message_rate >::value();
  }
  static const char* value(const ::beginner_tutorials::message_rateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MESSAGE_RATE_H
